before_install:
  - date
  - cd ${HOME}
  - sudo apt-get -qq -y install libgc-dev
  - sudo apt-get -qq -y install libgmp3-dev
  - sudo apt-get -qq -y install
  # For utils/atspkgreloc
  - wget https://s3.amazonaws.com/json-c_releases/releases/json-c-0.12-nodoc.tar.gz
  - tar xf json-c-0.12-nodoc.tar.gz
  - cd json-c-0.12
  - ./configure
  - make
  - sudo make install
  - export ATSHOME=${HOME}/ats-lang-anairiats-0.2.11
  - export ATSHOMERELOC=ATS-0.2.11
  - export PATSHOME=${TRAVIS_BUILD_DIR}
  - export PATSHOMERELOC=${TRAVIS_BUILD_DIR}
  - export PATH=${PATH}:${PATSHOME}/bin
  - ${TRAVIS_BUILD_DIR}/travis-ci/setup.sh 0.2.11
script:
  - cd ${TRAVIS_BUILD_DIR}
  # Test release process
  - make -f codegen/Makefile_atslib
  - make -f Makefile_devl src_depend
  - make -C ${PATSHOME}/src patsopt
  - make -C ${PATSHOME}/src CBOOT
  - make -C ${PATSHOME}/src/CBOOT/prelude
  - make -C ${PATSHOME}/src/CBOOT/libc
  - make -C ${PATSHOME}/src/CBOOT/libats
  - make -C ${PATSHOME}/doc/DISTRIB atspackaging
  - make -C ${PATSHOME}/doc/DISTRIB cleanall
  - make -C ${PATSHOME}/doc/DISTRIB atspacktarzvcf
  # Regress test
  - make -f Makefile_devl all
  - make -C ${PATSHOME}/doc regress > regress_doc.log 2>&1
  - tail -100 regress_doc.log
  # Build utils
  - make -C libatsynmark
  - make -C utils/atsynmark
  - make -C utils/atspkgreloc
  - make -C utils/atstags
  - make -C utils/atslex
after_script:
  - date
